name: solar-system cicd

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature
env:
    MONGO_URI: 'mongodb+srv://cluster0.zmsztvg.mongodb.net/superData'                                                                     `
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}                          
jobs:
    unit-testing:
      name: Unit Testing
      runs-on: ubuntu-latest 
      strategy:
        matrix:
          node-version: [18]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Install dependency
        uses: npm install 
    
      - name: unit test
        uses: npm test                                                                                                                 